# Generated by Django 3.2.25 on 2024-07-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RHBA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CVEs', models.TextField(blank=True, default='', null=True)),
                ('Patches', models.TextField(blank=True, default='', null=True)),
                ('RHBA', models.TextField(blank=True, default='', null=True)),
                ('CPE_list', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('description_cve', models.TextField(blank=True, default='', null=True)),
                ('criteria', models.TextField(blank=True, default='', null=True)),
                ('packages', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'db_table': 'RHBA',
                'ordering': ['pk'],
            },
        ),
    ]
