# Generated by Django 3.2.25 on 2024-07-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rhba',
            name='criterion',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
